# Generated by Django 4.2.7 on 2024-01-11 15:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('suradi', '0004_alter_kategori_banner_dua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='diskon',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Diskon = (%)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_empat',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_lima',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_satu',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_tiga',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
    ]
